"""
Response schemas for DRIPE v2.
Defines the full response contract per the MVP design.
"""
from typing import List, Optional, Dict
from pydantic import BaseModel, Field
from schemas.explanation import NoveltyBucket, EvidenceTier


class CoverageReport(BaseModel):
    graph_density_note: str
    literature_density_note: str
    trial_evidence_note: str
    known_limitations: List[str] = Field(default_factory=list)


class ScoreComponents(BaseModel):
    path_count: int = 0
    avg_path_confidence: float = 0.0
    literature_chunks: int = 0
    trial_count: int = 0
    gnn_raw_score: float = 0.0
    normalization_note: str = ""


class RankingScores(BaseModel):
    graph_score: float = 0.0
    learned_score: float = 0.0
    evidence_score: float = 0.0
    trial_score: float = 0.0
    composite_score: float = 0.0


class SupportingPath(BaseModel):
    path_type: str
    nodes: List[Dict]
    edges: List[Dict]
    path_confidence: float = 0.0
    provenance: List[str] = Field(default_factory=list)
    source_disease_context: Optional[str] = None


class RetrievedEvidence(BaseModel):
    source_type: str  # "pubmed" | "trial"
    identifier: str  # PMID or NCT ID
    title: str = ""
    snippet: str = ""
    year: int = 0
    relevance_score: float = 0.0


class CounterEvidence(BaseModel):
    type: str  # sparse_support, contradictory_signal, known_failure, missing_trial_context
    detail: str


class Explanation(BaseModel):
    structured_summary: str = ""
    plain_language_summary: str = ""
    uncertainty_statement: str = ""
    basis: Optional[Dict] = None


class Candidate(BaseModel):
    drug_name: str
    drug_id: str
    ranking_scores: RankingScores = Field(default_factory=RankingScores)
    score_components: Optional[ScoreComponents] = None
    novelty_bucket: NoveltyBucket = NoveltyBucket.EXPLORATORY
    supporting_paths: List[SupportingPath] = Field(default_factory=list)
    retrieved_evidence: List[RetrievedEvidence] = Field(default_factory=list)
    counter_evidence: List[CounterEvidence] = Field(default_factory=list)
    explanation: Optional[Explanation] = None


class ProgramScope(BaseModel):
    primary_disease: str = "rheumatoid arthritis"
    adjacent_diseases_considered: List[str] = Field(default_factory=list)


class QueryResponse(BaseModel):
    query: Dict
    program_scope: ProgramScope = Field(default_factory=ProgramScope)
    coverage_report: CoverageReport = Field(default_factory=CoverageReport)
    candidates: List[Candidate] = Field(default_factory=list)
    research_only_disclaimer: str = "RESEARCH USE ONLY. This output is a computational hypothesis generated by an automated knowledge graph reasoning pipeline. It does not constitute medical advice."

    class Config:
        json_schema_extra = {
            "example": {
                "query": {"disease_input": "rheumatoid arthritis", "canonical_disease_id": "C0003873", "query_status": "accepted"},
                "candidates": []
            }
        }
