DISCLAIMER_TEXT = (
    "RESEARCH USE ONLY. This output is a computational hypothesis generated by an automated "
    "knowledge graph reasoning pipeline. It has not been validated through in vitro experiments, "
    "animal studies, or clinical trials. It does not constitute medical advice. It must not be "
    "used to inform treatment decisions for any patient. The next required step before this "
    "hypothesis has any scientific standing is experimental validation by qualified researchers "
    "in an appropriate laboratory setting."
)

def inject_disclaimer(data: dict) -> dict:
    """Appends the mandatory disclaimer to any output dictionary."""
    data["disclaimer"] = DISCLAIMER_TEXT
    return data
